# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.hostname = 'moodle.local'
	config.vm.box = "ubuntu/xenial64"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.synced_folder ".", "/vagrant", create: true
	config.vm.synced_folder "./moodle/", "/var/www/moodle", create: true, owner: 'www-data', group: 'www-data'
	config.vm.provider "virtualbox" do |vb|
		vb.name = "moodle"
		vb.memory = 1024
		vb.cpus = 2
	end
	config.vm.provision "shell", inline: <<-SHELL
  if [ ! -d "$HOME/.rbenv" ]; then
      echo "Installing rbenv and ruby-build"
      git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
      git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
      echo ‘Adding rbenv to path’
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      git clone https://github.com/rbenv/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
    else
      echo "Updating rbenv and ruby-build"
      cd ~/.rbenv
      git pull
      cd ~/.rbenv/plugins/ruby-build
      git pull
    fi
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    if [ ! -d "$HOME/.rbenv/versions/2.4.0" ]; then
      echo "Installing ruby"
      rbenv install 2.4.0
      rbenv global 2.4.0
      gem update --system
      gem update
      gem install bundler
      bundle config path vendor/bundle
      rbenv rehash
      curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
      sudo apt-get install -y nodejs
      
      version="5.0.1"
      gem install rails --version=${version} --no-ri --no-rdoc --verbose
      rbenv rehash
    fi
		sudo bash /vagrant/provision.sh
	SHELL
end